# Generated by Django 4.1.5 on 2023-01-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('DV', 'In develop'), ('FN', 'Finished'), ('RV', 'Under review'), ('DL', 'Deleted')], default='PN', max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('PG', 'In progress'), ('SV', 'Solved'), ('PS', 'Paused'), ('DL', 'Deleted')], default='PN', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='const_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('PG', 'In progress'), ('SV', 'Solved'), ('PS', 'Paused'), ('DL', 'Deleted')], default='PN', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('const_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('PG', 'In progress'), ('SV', 'Solved'), ('PS', 'Paused'), ('DL', 'Deleted')], default='PN', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_actions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_actions', to='project.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
