version: '3.7'

services:

  db:
    container_name: timeline-psql
    image: 'postgres:${POSTGRES_TAG}'
    restart: 'no'
    env_file:
      - .env
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - timeline-psql:/var/lib/postgresql/data

  redis:
    container_name: timeline-redis
    image: redis:${REDIS_TAG}
    restart: 'always'
    env_file:
      - .env
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - timeline-redis:/data

  api:
    container_name: timeline-api
    image: python:${PYTHON_TAG}
    depends_on:
      - db
      - redis
    env_file:
      - .env
    build:
      context: backend/
      args:
        TAG: ${PYTHON_TAG}
    command: sh -c 'python manage.py runserver $PYTHON_HOST:$PYTHON_PORT'
    ports:
      - 8000:${PYTHON_PORT}
      - 430:${PYTHON_PORT}
    volumes:
      - ./backend:/app

volumes:
  timeline-psql:
  timeline-redis:
